name: xayn_card_view_example
description: Card view example by Xayn.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  xayn_card_view:
    path: ../../xayn_card_view

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 1.0.4
