name: kitty_app
description: Card view example that displays cat images in cards by Xayn.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  xayn_card_view:
    path: ../../xayn_card_view
  shimmer: 2.0.0
  http: 0.13.4
  font_awesome_flutter: 10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 2.0.1
