name: xayn_card_view
description: Card view provided by Xayn.
version: 0.0.1
homepage: https://github.com/xaynetwork
repository: https://github.com/xaynetwork/xayn_card_view
issue_tracker: https://github.com/xaynetwork/xayn_card_view/issues

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: 1.0.4
